# Generated by Django 5.2.17 on 2026-10-06 02:56

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(default=reports.models.new_folio, editable=False, max_length=15, unique=True)),
                ('client_request_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('lost', 'Perdí algo'), ('found', 'Encontré algo')], max_length=5)),
                ('category', models.CharField(choices=[('bag', 'Bolsa o mochila'), ('clothing', 'Ropa'), ('accessory', 'Accesorio'), ('book', 'Libro o cuaderno'), ('other', 'Otro objeto no sensible')], max_length=16)),
                ('description', models.CharField(max_length=300)),
                ('approximate_area', models.CharField(max_length=120)),
                ('occurred_on', models.DateField()),
                ('holder', models.CharField(blank=True, choices=[('finder', 'Lo conserva quien lo encontró')], max_length=16)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_clue', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private', to='reports.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('owner', 'client_request_id'), name='unique_report_request_per_owner'),
        ),
    ]
