# Generated by Django 5.2.17 on 2026-10-06 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='public_area',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='report',
            name='public_summary',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='report',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Privado'), ('pending', 'Pendiente de revisión'), ('public', 'Publicado'), ('rejected', 'Rechazado')], default='private', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='holder',
            field=models.CharField(blank=True, choices=[('finder', 'Lo conserva quien lo encontró'), ('point', 'Punto de resguardo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('reserved', 'Reclamación aprobada'), ('returned', 'Entrega registrada'), ('closed', 'Cerrado')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['publication_status', 'status', 'kind', 'category', 'occurred_on'], name='report_public_search_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'kind', 'category', 'occurred_on'], name='report_matching_idx'),
        ),
    ]
