# Generated by Django 5.2.17 on 2026-10-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_public_area_report_public_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='publication_review_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
