# Generated by Django 5.2.17 on 2026-10-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_report_public_area_report_public_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('submitted', 'Enviada'), ('disputed', 'En disputa'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='submitted', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_claims', to=settings.AUTH_USER_MODEL)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='reports.report')),
                ('lost_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_from_loss', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='claim_review_idx')],
                'constraints': [models.UniqueConstraint(fields=('found_report', 'claimant'), name='one_claim_per_user_and_found'), models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('found_report',), name='one_approved_claim_per_found')],
            },
        ),
    ]
