# Generated by Django 5.2.17 on 2026-10-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('reports', '0002_report_public_area_report_public_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public_area', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='custody_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('intake', 'Recepción'), ('transfer', 'Traslado'), ('handover_started', 'Entrega iniciada'), ('handover_confirmed', 'Entrega confirmada')], max_length=24)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='reports.report')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custody.custodypoint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custody.custodypoint')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custody_record', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmada por reclamante')], default='pending', max_length=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handover', to='claims.claim')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_handovers', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custody.custodypoint')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handover', to='reports.report')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
